---
apiVersion: v1
kind: Secret
metadata:
  name: csi-cephfs-secret
  namespace: ceph-csi
stringData:
  # Required for statically provisioned volumes
  userID: admin
  userKey: AQAiKYthyDQPNRAAnb2dHVUWEcc6j9KPA9yqOA==

  # Required for dynamically provisioned volumes
  adminID: admin
  adminKey: AQAiKYthyDQPNRAAnb2dHVUWEcc6j9KPA9yqOA==
