---
apiVersion: v1
kind: Secret
metadata:
  name: csi-rbd-secret
  namespace: rbd-provisioner
stringData:
  # Key values correspond to a user name and its key, as defined in the
  # ceph cluster. User ID should have required access to the 'pool'
  # specified in the storage class
  userID: admin
  userKey: AQA5K0RiMQS/HhAAXeamoqPYM04jLGmot3bCUg==

  # Encryption passphrase
  encryptionPassphrase: test_passphrase
